### ISSUE TITLE
Default background color isn't applied to HACS's page

### ISSUE THREAD

**Issue by guice** [fi-sch/ux_goodie_theme#4]
See screenshot, the default dark background isn't applied to this page:

<img width="1627" alt="Screen Shot 2020-01-25 at 9 25 30 AM" src="https://user-images.githubusercontent.com/205378/73124130-ee894e00-3f54-11ea-87e5-f8c652d386c6.png">

**Comment by fi-sch** [comment]
Strange. It should the either the same background that you use for Lovelace UI or system-wide default (#2e2e2e in my theme). Looks like it neither background-image is applied, nor 'var(--primary-background-color)' is.
I want to look into this but need some more data as I don't see that issue on my setup. Even if I intentionally break background-image property.

1. Do you use any background image for your setup?
2. Can you provide CSS styles applied to < app-header-layout > (check via dev tools)?
3. Do you have any problem like that with other themes?
4. Have you tried using different browser or clearing the cache?

**Comment by guice** [comment]
Looks like it's this setting that's causing it:

```
--lovelace-background: center / cover no-repeat url("/local/background.jpg") fixed;
```
![Screen Shot 2020-01-26 at 10 45 31 AM](https://user-images.githubusercontent.com/205378/73139234-295cb600-4029-11ea-8b13-4b8bbc0a283f.png)

I've never set any background image.

I see this in `ux-goodie` theme:

```
➜  config grep -in lovelace-background themes/* 
themes/ux_goodie.yaml:5:  lovelace-background: 'center / cover no-repeat url("/local/background.jpg") fixed'
```

I'm thinking this is it?

**Comment by fi-sch** [comment]
Yup, that's it. I'm glad that you solved this problem by yourself.

BTW, it was mentioned in readme before to put background.jpg into /config/www/ directory. Therefore I'm closing this issue :) 

PS You can just edit ux-goodie.yaml and remove that one line from it.

**Comment by guice** [comment]
> BTW, it was mentioned in readme before to put background.jpg into /config/www/ directory. Therefore I'm closing this issue :)

I know. I don't have or use a background, so I skipped it. Why make users put in a background if they don't use one?

Oh, I see, because you want them to disable, vs enable:

> Alternatively, if you don't want to use any background just comment the 5th line of ux_goodie.yaml

**Comment by fi-sch** [comment]
I've just added this last sentence (that you quoted) to make things clear.
What I assumed is that many users who would use this theme, will also use some background image. That is why I left this one line and described usage in Installation section.

Maybe I've shouldn't – that's hard to say. Anyways, I wouldn't change that right now. I just don't want to break the setup for those who already installed my theme with their own backgrounds :)
